[package]
name = "2019"
version = "0.1.0"
authors = ["Andres <andresnrx@gmail.com>"]
edition = "2018"

[dependencies]
common = { path = "../common" }
intcode = { path = "../intcode" }
itertools = "0.8.2"
regex = "1.3.1"
lazy_static = "1.4.0"
enum-map = "0.6.1"
