[package]
name = "twenty-nineteen"
version = "0.1.0"
authors = ["Andres <andresnrx@gmail.com>"]
edition = "2021"

[dependencies]
common = { path = "../common" }
intcode = { path = "../intcode" }
itertools = "0.10.1"
regex = "1.5.4"
lazy_static = "1.4.0"
enum-map = "1.1.1"
