[package]
name = "twenty-nineteen"
version = "0.1.0"
authors = ["Andres <andresnrx@gmail.com>"]
edition = "2018"

[dependencies]
common = { path = "../common" }
intcode = { path = "../intcode" }
itertools = "0.9.0"
regex = "1.4.2"
lazy_static = "1.4.0"
enum-map = "0.6.4"
