[package]
name = "2019"
version = "0.1.0"
authors = ["Andres <andresnrx@gmail.com>"]
edition = "2018"

[dependencies]
common = { path = "../common" }
intcode = { path = "../intcode" }
itertools = "0.8.2"
