[package]
name = "twenty-fifteen"
version = "0.1.0"
authors = ["Andres <andresnrx@gmail.com>"]
edition = "2021"

[dependencies]
common = { path = "../common" }
lazy_static = "1.4.0"
regex = "1.5.4"
md5 = "0.7.0"
bit-vec = "0.6.3"
serde_json = "1.0.68"
