[package]
name = "2015"
version = "0.1.0"
authors = ["Andres <andresnrx@gmail.com>"]
edition = "2018"

[dependencies]
common = { path = "../common" }
lazy_static = "1.4.0"
regex = "1.3.1"
md5 = "0.7.0"
bit-vec = "0.6.1"
