[package]
name = "common"
version = "0.1.0"
authors = ["Andres <andresnrx@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cookie = "0.14.3"
reqwest = { version = "0.10.9", features = ["blocking"] }
